export const optionsByType = {
  string: [
    { value: "$eq", label: "is" },
    { value: "$ne", label: "is not" },
    { value: "$null", label: "is null" },
    { value: "$notNull", label: "is not null" },
    { value: "$eqi", label: "is (case insensitive)" },
    { value: "$nei", label: "is not (case insensitive)" },
    { value: "$contains", label: "contains" },
    { value: "$containsi", label: "contains (case insensitive)" },
    { value: "$notContains", label: "does not contain" },
    {
      value: "$notContainsi",
      label: "does not contain (case insensitive)",
    },
    { value: "$startsWith", label: "starts with" },
    { value: "$startsWithi", label: "starts with (case insensitive)" },
    { value: "$endsWith", label: "ends with" },
    { value: "$endsWithi", label: "ends with (case insensitive)" },
  ],
  relation: [
    { value: "$eq", label: "is" },
    { value: "$ne", label: "is not" },
    { value: "$null", label: "is null" },
    { value: "$notNull", label: "is not null" },
    { value: "$eqi", label: "is (case insensitive)" },
    { value: "$nei", label: "is not (case insensitive)" },
    { value: "$contains", label: "contains" },
    { value: "$containsi", label: "contains (case insensitive)" },
    { value: "$notContains", label: "does not contain" },
    {
      value: "$notContainsi",
      label: "does not contain (case insensitive)",
    },
    { value: "$startsWith", label: "starts with" },
    { value: "$startsWithi", label: "starts with (case insensitive)" },
    { value: "$endsWith", label: "ends with" },
    { value: "$endsWithi", label: "ends with (case insensitive)" },
  ],
  email: [
    { value: "$eq", label: "is" },
    { value: "$ne", label: "is not" },
    { value: "$null", label: "is null" },
    { value: "$notNull", label: "is not null" },
    { value: "$eqi", label: "is (case insensitive)" },
    { value: "$nei", label: "is not (case insensitive)" },
    { value: "$contains", label: "contains" },
    { value: "$containsi", label: "contains (case insensitive)" },
    { value: "$notContains", label: "does not contain" },
    {
      value: "$notContainsi",
      label: "does not contain (case insensitive)",
    },
    { value: "$startsWith", label: "starts with" },
    { value: "$startsWithi", label: "starts with (case insensitive)" },
    { value: "$endsWith", label: "ends with" },
    { value: "$endsWithi", label: "ends with (case insensitive)" },
  ],
  enumeration: [
    { value: "$eq", label: "is" },
    { value: "$ne", label: "is not" },
    { value: "$null", label: "is null" },
    { value: "$notNull", label: "is not null" },
  ],
  number: [
    { value: "equals", label: "Equals" },
    { value: "greaterThan", label: "Greater Than" },
    { value: "lessThan", label: "Less Than" },
  ],
  float: [
    { value: "equals", label: "Equals" },
    { value: "greaterThan", label: "Greater Than" },
    { value: "lessThan", label: "Less Than" },
  ],
  datetime: [
    { value: "$eq", label: "is" },
    { value: "$ne", label: "is not" },
    { value: "$null", label: "is null" },
    { value: "$notNull", label: "is not null" },
    { value: "$gt", label: "is greater than" },
    { value: "$gte", label: "is greater than or equal to" },
    { value: "$lt", label: "is lower than" },
    { value: "$lte", label: "is lower than or equal to" },
  ],
};