import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
import "../style/css/feather.css";
import "../index.scss";
import "../style/icon/boxicons/boxicons/css/boxicons.min.css";
import "../style/icon/weather/weathericons.css";
import "../style/icon/typicons/typicons.css";
import "../style/icon/fontawesome/css/fontawesome.min.css";
import "../style/icon/fontawesome/css/all.min.css";
import "../style/icon/ionic/ionicons.css";
import "../style/icon/tabler-icons/webfont/tabler-icons.css";
import '../style/css/custom_style.css'

export const metadata = {
  title: "CRM App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], weight: ["400", "600", "700"] });

export default function RootLayout({ children, locale }) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
